package es.unileon.prg1.blablakid
/* Generated by dia/codegen.py
 *
 * Generated files:
 *	/home/pablo/progra1/blablakids/Week.java
 *	/home/pablo/progra1/blablakids/Activities.java
 *	/home/pablo/progra1/blablakids/Kids.java
 *	/home/pablo/progra1/blablakids/Hour.java
 *	/home/pablo/progra1/blablakids/Parent.java
 *	/home/pablo/progra1/blablakids/Ride.java
 *	/home/pablo/progra1/blablakids/Place.java
 *	/home/pablo/progra1/blablakids/Parents.java
 *	/home/pablo/progra1/blablakids/Activity.java
 *	/home/pablo/progra1/blablakids/Textui.java
 *	/home/pablo/progra1/blablakids/Rides.java
 *	/home/pablo/progra1/blablakids/Day.java
 *	/home/pablo/progra1/blablakids/Blablakids app.java
 *	/home/pablo/progra1/blablakids/Kid.java
 */
